
let mapleader = ","

map <c-j> <c-w>j
map <c-j> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

noremap <C-Z> :update<CR>
vnoremap <C-Z> <C-C>:update<CR>
inoremap <C-Z> <C-O>:update<CR>

noremap <Leader>e :quit<CR>
noremap <Leader>E :qa!<CR>

set nobackup
set nowritebackup
set noswapfile

set t_Co=256

filetype off
call pathogen#infect()
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
filetype plugin indent on
syntax on
map <C-t> :NERDTreeToggle<CR>

let g:pep8_map='<leader>8'

set number  " show line numbers
set tw=79   " width of document (used by gd)
set nowrap  " don't automatically wrap on load
set fo-=t   " don't automatically wrap text when typing

highlight ColorColumn ctermbg=233

set laststatus=2
let g:ctrlp_max_height = 30
set wildignore+=*.pyc
set wildignore+=*_build/*
set wildignore+=*/coverage/*
set pastetoggle=<F2>
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set foldmethod=indent
set foldlevel=99

map <leader>g :GundoToggle<CR>

noremap <Leader>g :RopeGotoDefinition<CR>
noremap <Leader>v :RopeExtractVariable<CR>
noremap <Leader>m :RopeExtractMethod<CR>
noremap <Leader>n :RopeRename<CR>

colorscheme github

